### 1. Tambah Catatan Baru (POST)
POST https://notes-backend-514828886605.us-central1.run.app/api/notes
Content-Type: application/json

{
    "judul": "Catatan ABIS LEBARAN",
    "isi": "Lorem Ipsum"
}


### 2. Lihat Semua Catatan (GET)
GET https://notes-backend-514828886605.us-central1.run.app/api/notes/:2


### 3. Edit Catatan (PUT)
PUT http://localhost:3000/api/notes/5
Content-Type: application/json

{
    "judul": "Catatan 5 Diedit",
    "isi": "Isi catatan nomor 5 sudah DIEDIT."
}


### 4. Hapus Catatan (DELETE)
DELETE http://localhost:3000/api/notes/5